# Generates pilot .env secrets and syncs enrollment public key to the Windows Terminal.
# Usage: pwsh -File scripts/Generate-PilotEnv.ps1

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot

$genDir = Join-Path $env:TEMP "WebPosPilotEnvGen"
New-Item -ItemType Directory -Force -Path $genDir | Out-Null

@'
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
'@ | Set-Content (Join-Path $genDir "PilotEnvGen.csproj") -Encoding utf8

@"
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

string root = args[0];
using RSA rsa = RSA.Create(3072);
string privatePem = rsa.ExportPkcs8PrivateKeyPem();
string publicPem = rsa.ExportSubjectPublicKeyInfoPem();
string EscapeEnv(string pem) => pem.Replace("\r\n", "\n").Replace("\n", "\\n");

byte[] pinKey = RandomNumberGenerator.GetBytes(32);
byte[] jwtKeyBytes = RandomNumberGenerator.GetBytes(48);
string postgresPassword = Convert.ToBase64String(RandomNumberGenerator.GetBytes(18))
    .Replace("+", "x").Replace("/", "y").TrimEnd('=');

const string cashierPin = "2468";
const string adminPassword = "admin123";

File.WriteAllText(Path.Combine(root, ".env"), string.Join('\n',
    "# Generated by scripts/Generate-PilotEnv.ps1 — do not commit",
    `$"POSTGRES_PASSWORD={postgresPassword}",
    `$"SECURITY_PIN_HASH_KEY={Convert.ToBase64String(pinKey)}",
    `$"SECURITY_JWT_KEY={Convert.ToBase64String(jwtKeyBytes)}",
    `$"SECURITY_ENROLLMENT_PRIVATE_KEY_PEM={EscapeEnv(privatePem)}",
    `$"SECURITY_ENROLLMENT_PUBLIC_KEY_PEM={EscapeEnv(publicPem)}",
    "PILOT_TERMINAL_ID=00000000-0000-0000-0000-000000000010",
    `$"PILOT_ADMIN_PASSWORD={adminPassword}",
    `$"PILOT_CASHIER_PIN={cashierPin}",
    ""), Encoding.UTF8);

var terminalSettings = new
{
    WebPosSdk = new { BaseAddress = "http://localhost:8080/", ApiVersion = "1.0.0" },
    Security = new { Enrollment = new { PublicKeyPem = publicPem.Replace("\r\n", "\n") } }
};
File.WriteAllText(
    Path.Combine(root, "WebPos.WindowsTerminal", "appsettings.json"),
    JsonSerializer.Serialize(terminalSettings, new JsonSerializerOptions { WriteIndented = true }),
    Encoding.UTF8);

Console.WriteLine("Wrote .env and WebPos.WindowsTerminal/appsettings.json");
Console.WriteLine($"Pilot cashier PIN: {cashierPin}");
Console.WriteLine($"Pilot admin password: {adminPassword}");
"@ | Set-Content (Join-Path $genDir "Program.cs") -Encoding utf8

# Fix accidental PowerShell escaping of $ in here-string — rewrite Program.cs cleanly
@'
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

string root = args[0];
using RSA rsa = RSA.Create(3072);
string privatePem = rsa.ExportPkcs8PrivateKeyPem();
string publicPem = rsa.ExportSubjectPublicKeyInfoPem();
string EscapeEnv(string pem) => pem.Replace("\r\n", "\n").Replace("\n", "\\n");

byte[] pinKey = RandomNumberGenerator.GetBytes(32);
byte[] jwtKeyBytes = RandomNumberGenerator.GetBytes(48);
string postgresPassword = Convert.ToBase64String(RandomNumberGenerator.GetBytes(18))
    .Replace("+", "x").Replace("/", "y").TrimEnd('=');

const string cashierPin = "2468";
const string adminPassword = "admin123";

File.WriteAllText(Path.Combine(root, ".env"), string.Join('\n',
    "# Generated by scripts/Generate-PilotEnv.ps1 — do not commit",
    $"POSTGRES_PASSWORD={postgresPassword}",
    $"SECURITY_PIN_HASH_KEY={Convert.ToBase64String(pinKey)}",
    $"SECURITY_JWT_KEY={Convert.ToBase64String(jwtKeyBytes)}",
    $"SECURITY_ENROLLMENT_PRIVATE_KEY_PEM={EscapeEnv(privatePem)}",
    $"SECURITY_ENROLLMENT_PUBLIC_KEY_PEM={EscapeEnv(publicPem)}",
    "PILOT_TERMINAL_ID=00000000-0000-0000-0000-000000000010",
    $"PILOT_ADMIN_PASSWORD={adminPassword}",
    $"PILOT_CASHIER_PIN={cashierPin}",
    ""), Encoding.UTF8);

var terminalSettings = new
{
    WebPosSdk = new { BaseAddress = "http://localhost:8080/", ApiVersion = "1.0.0" },
    Security = new { Enrollment = new { PublicKeyPem = publicPem.Replace("\r\n", "\n") } }
};
File.WriteAllText(
    Path.Combine(root, "WebPos.WindowsTerminal", "appsettings.json"),
    JsonSerializer.Serialize(terminalSettings, new JsonSerializerOptions { WriteIndented = true }),
    Encoding.UTF8);

// Gitignored local override so `dotnet run` Master shares Docker Postgres (WebPos + .env password).
var developmentLocal = new Dictionary<string, object?>
{
    ["ConnectionStrings"] = new Dictionary<string, string>
    {
        ["DefaultConnection"] =
            $"Server=localhost;Port=5432;Database=WebPos;User Id=postgres;Password={postgresPassword};"
    }
};
File.WriteAllText(
    Path.Combine(root, "WebPos", "appsettings.Development.Local.json"),
    JsonSerializer.Serialize(developmentLocal, new JsonSerializerOptions { WriteIndented = true }),
    Encoding.UTF8);

// Local host run when Docker Hub is unavailable (gitignored).
var pilotApiSettings = new Dictionary<string, object?>
{
    ["ConnectionStrings"] = new Dictionary<string, string>
    {
        ["DefaultConnection"] =
            $"Server=localhost;Port=5432;Database=WebPos;User Id=postgres;Password={postgresPassword};"
    },
    ["Security"] = new Dictionary<string, object?>
    {
        ["PinHashKey"] = Convert.ToBase64String(pinKey),
        ["Enrollment"] = new Dictionary<string, object?>
        {
            ["PrivateKeyPem"] = privatePem.Replace("\r\n", "\n"),
            ["PublicKeyPem"] = publicPem.Replace("\r\n", "\n"),
            ["LifetimeDays"] = 365
        },
        ["Jwt"] = new Dictionary<string, object?>
        {
            ["Key"] = Convert.ToBase64String(jwtKeyBytes),
            ["Issuer"] = "WebPos",
            ["Audience"] = "WebPos.Api",
            ["AccessTokenLifetimeMinutes"] = 60
        }
    },
    ["Pilot"] = new Dictionary<string, string>
    {
        ["TerminalId"] = "00000000-0000-0000-0000-000000000010",
        ["AdminPassword"] = adminPassword,
        ["CashierPin"] = cashierPin
    }
};
File.WriteAllText(
    Path.Combine(root, "WebPos", "appsettings.Pilot.json"),
    JsonSerializer.Serialize(pilotApiSettings, new JsonSerializerOptions { WriteIndented = true }),
    Encoding.UTF8);

Console.WriteLine("Wrote .env, Development.Local.json, appsettings.Pilot.json, and Windows Terminal appsettings.json");
Console.WriteLine($"Pilot cashier PIN: {cashierPin}");
Console.WriteLine($"Pilot admin password: {adminPassword}");
Console.WriteLine("Master + Terminal: use http://localhost:8080 (same Database=WebPos)");
'@ | Set-Content (Join-Path $genDir "Program.cs") -Encoding utf8

dotnet run --project (Join-Path $genDir "PilotEnvGen.csproj") -- $root
