// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebPos.Core.Data;

#nullable disable

namespace WebPos.Migrations
{
    [DbContext(typeof(WebPosDbContext))]
    [Migration("20260807110122_AddPosDisplayNameAndPurchaseUnit")]
    partial class AddPosDisplayNameAndPurchaseUnit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebPos.Core.Models.CashAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PaymentMethodKey")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("payment_method_key");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TerminalId")
                        .HasColumnType("uuid")
                        .HasColumnName("terminal_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_type");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TerminalId");

                    b.HasIndex("TenantId", "AccountCode")
                        .IsUnique()
                        .HasDatabaseName("UX_cash_accounts_tenant_account_code");

                    b.HasIndex("TenantId", "TerminalId")
                        .IsUnique()
                        .HasDatabaseName("UX_cash_accounts_tenant_terminal")
                        .HasFilter("\"terminal_id\" IS NOT NULL");

                    b.HasIndex("TenantId", "Type", "SortOrder")
                        .HasDatabaseName("IX_cash_accounts_tenant_type_sort");

                    b.ToTable("cash_accounts", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.CashierShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("ActualBlindCashPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("actual_blind_cash_paisa");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("uuid")
                        .HasColumnName("cashier_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<long>("DiscrepancyPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("discrepancy_paisa");

                    b.Property<long>("ExpectedCashPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_cash_paisa");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<long>("OpeningCashPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("opening_cash_paisa");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("uuid")
                        .HasColumnName("terminal_id");

                    b.HasKey("Id");

                    b.HasIndex("CashierId")
                        .IsUnique()
                        .HasDatabaseName("UX_cashier_shifts_open_cashier")
                        .HasFilter("\"status\" = 'OPEN'");

                    b.HasIndex("TenantId");

                    b.HasIndex("TerminalId")
                        .IsUnique()
                        .HasDatabaseName("UX_cashier_shifts_open_terminal")
                        .HasFilter("\"status\" = 'OPEN'");

                    b.ToTable("cashier_shifts", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<bool>("ShowOnWebshop")
                        .HasColumnType("boolean")
                        .HasColumnName("show_on_webshop");

                    b.Property<int>("TargetMarginPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("target_margin_percentage");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("TenantId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.DailyMilkCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CollectionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collection_time");

                    b.Property<decimal?>("FatPercent")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("fat_percent");

                    b.Property<decimal>("LitersReceived")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("liters_received");

                    b.Property<string>("MilkType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("milk_type");

                    b.Property<long>("RatePerLiterPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("rate_per_liter_paisa");

                    b.Property<decimal?>("SnfPercent")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("snf_percent");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("TotalCreditPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("total_credit_paisa");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("TenantId");

                    b.ToTable("daily_milk_collections", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.DamagedStockLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTimeOffset>("LoggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at");

                    b.Property<Guid>("LoggedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("logged_by");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reason_code");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("WriteOffLossPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("write_off_loss_paisa");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("LoggedBy");

                    b.HasIndex("ProductId");

                    b.HasIndex("TenantId");

                    b.ToTable("damaged_stock_logs", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.GeneralLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreditPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("credit_paisa");

                    b.Property<long>("DebitPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("debit_paisa");

                    b.Property<Guid?>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<string>("ReferenceDetails")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reference_details");

                    b.Property<string>("ReferenceNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_no");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TransactionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_group_id");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id");

                    b.HasIndex("AccountCode");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ReferenceNo");

                    b.HasIndex("TenantId");

                    b.HasIndex("TransactionGroupId");

                    b.ToTable("general_ledger_entries", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreditLimitPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("credit_limit_paisa");

                    b.Property<long>("CurrentBalancePaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("current_balance_paisa");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("party_type");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_parties_tenant_phone");

                    b.HasIndex("TenantId", "UpdatedAt")
                        .HasDatabaseName("IX_parties_tenant_updated_at");

                    b.HasIndex("TenantId", "PartyType", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_parties_tenant_type_name");

                    b.ToTable("parties", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.PartyLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreditPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("credit_paisa");

                    b.Property<long>("DebitPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("debit_paisa");

                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("invoice_no");

                    b.Property<long>("NewBalancePaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("running_balance_paisa");

                    b.Property<long>("OldBalancePaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("old_balance_paisa");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_id");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_channel");

                    b.Property<Guid?>("PurchaseOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_order_id");

                    b.Property<string>("ReferenceDetails")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_number");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("TransactionAmountPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_paisa");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNo");

                    b.HasIndex("PartyId");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("TenantId");

                    b.ToTable("party_ledgers", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.PartyPaymentAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_paisa");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("invoice_no");

                    b.Property<Guid>("PartyLedgerId")
                        .HasColumnType("uuid")
                        .HasColumnName("party_ledger_id");

                    b.Property<Guid?>("PurchaseOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_order_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNo");

                    b.HasIndex("PartyLedgerId")
                        .HasDatabaseName("IX_party_payment_allocations_party_ledger_id");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("TenantId");

                    b.ToTable("party_payment_allocations", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("barcode");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("base_unit");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<int>("ConversionMultiplier")
                        .HasColumnType("integer")
                        .HasColumnName("conversion_multiplier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsLoose")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_loose");

                    b.Property<decimal>("MinStockQty")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasDefaultValue(10m)
                        .HasColumnName("min_stock_qty");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PurchaseUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("")
                        .HasColumnName("purchase_unit");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("")
                        .HasColumnName("short_code");

                    b.Property<bool>("ShowOnWebshop")
                        .HasColumnType("boolean")
                        .HasColumnName("show_on_webshop");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ShortCode")
                        .IsUnique()
                        .HasFilter("short_code <> ''");

                    b.HasIndex("TenantId", "UpdatedAt")
                        .HasDatabaseName("IX_products_tenant_updated_at");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.ProductBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("batch_number");

                    b.Property<long>("CostPricePaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("cost_price_paisa");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentQty")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("current_qty");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<decimal>("InitialQty")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("initial_qty");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid?>("PurchaseOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_order_id");

                    b.Property<string>("RackLocation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rack_location");

                    b.Property<long>("RetailPricePaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("retail_price_paisa");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("TenantId");

                    b.ToTable("product_batches", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.ProductionConsumptionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("ProductionLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_log_id");

                    b.Property<decimal>("QuantityConsumed")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity_consumed");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductionLogId");

                    b.HasIndex("TenantId");

                    b.ToTable("production_consumption_items", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.ProductionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AdditionalOverheadPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("additional_overhead_paisa");

                    b.Property<string>("BatchReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("batch_reference");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("BatchReference")
                        .IsUnique();

                    b.HasIndex("OperatorId");

                    b.HasIndex("TenantId");

                    b.ToTable("production_logs", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.ProductionYieldItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("CalculatedCostPricePaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("calculated_cost_price_paisa");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("ProductionLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_log_id");

                    b.Property<decimal>("QuantityProduced")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity_produced");

                    b.Property<Guid?>("TargetBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_batch_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductionLogId");

                    b.HasIndex("TargetBatchId");

                    b.HasIndex("TenantId");

                    b.ToTable("production_yield_items", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.PurchaseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("batch_number");

                    b.Property<decimal>("BonusQuantity")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("bonus_quantity");

                    b.Property<long>("CostPricePerUnitPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("cost_price_per_unit_paisa");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_order_id");

                    b.Property<decimal>("QuantityReceived")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity_received");

                    b.Property<string>("RackLocation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rack_location");

                    b.Property<long>("RetailPricePerUnitPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("retail_price_per_unit_paisa");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("TenantId");

                    b.ToTable("purchase_items", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountPaidPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_paid_paisa");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DiscountPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("discount_paisa");

                    b.Property<bool>("IsReceived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_received");

                    b.Property<long>("NetPayablePaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("net_payable_paisa");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_status");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_id");

                    b.Property<long>("SubTotalPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("sub_total_paisa");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("SupplierInvoiceNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("supplier_invoice_no");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("TenantId");

                    b.ToTable("purchase_orders", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.PurchaseReturn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<Guid>("OriginalPurchaseOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_purchase_order_id");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("TotalCreditDeductionPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("total_credit_deduction_paisa");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("OriginalPurchaseOrderId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("TenantId");

                    b.ToTable("purchase_returns", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.PurchaseReturnItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<long>("CostPerUnitPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("cost_per_unit_paisa");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("PurchaseReturnId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_return_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseReturnId");

                    b.HasIndex("TenantId");

                    b.ToTable("purchase_return_items", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.SalesInvoice", b =>
                {
                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("invoice_no");

                    b.Property<long>("AmountPaidPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_paid_paisa");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("uuid")
                        .HasColumnName("cashier_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<long>("DiscountAmountPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("discount_amount_paisa");

                    b.Property<string>("DiscountReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("discount_reason");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("receipt_number");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id");

                    b.Property<long>("TaxAmountPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("tax_amount_paisa");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TerminalId")
                        .HasColumnType("uuid")
                        .HasColumnName("terminal_id");

                    b.Property<long>("TotalAmountPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("total_amount_paisa");

                    b.HasKey("InvoiceNo");

                    b.HasIndex("CashierId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TerminalId");

                    b.ToTable("sales_invoices", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.SalesItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<long>("DiscountAppliedPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("discount_applied_paisa");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("invoice_no");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("UnitCostPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_cost_paisa");

                    b.Property<long>("UnitPricePaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_price_paisa");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("InvoiceNo");

                    b.HasIndex("ProductId");

                    b.HasIndex("TenantId");

                    b.ToTable("sales_items", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.SalesReturn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("uuid")
                        .HasColumnName("cashier_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("OriginalInvoiceNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("original_invoice_no");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("TotalRefundPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("total_refund_paisa");

                    b.HasKey("Id");

                    b.HasIndex("CashierId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OriginalInvoiceNo");

                    b.HasIndex("TenantId");

                    b.ToTable("sales_returns", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.SalesReturnItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<long>("RefundUnitPricePaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("refund_unit_price_paisa");

                    b.Property<string>("ReturnCondition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("return_condition");

                    b.Property<Guid>("SalesReturnId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_return_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesReturnId");

                    b.HasIndex("TenantId");

                    b.ToTable("sales_return_items", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.ShiftExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountPaisa")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_paisa");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExpenseCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("expense_category");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring");

                    b.Property<DateTimeOffset>("LoggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at");

                    b.Property<Guid>("LoggedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("logged_by_user_id");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_method");

                    b.Property<string>("ReceiptReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("receipt_reference");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("VoucherNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("voucher_no");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseCategory");

                    b.HasIndex("LoggedByUserId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("TenantId");

                    b.HasIndex("VoucherNo")
                        .IsUnique();

                    b.ToTable("shift_expenses", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PosDisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("")
                        .HasColumnName("pos_display_name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.Terminal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("LastSyncTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_time");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mac_address");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TerminalName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("terminal_name");

                    b.HasKey("Id");

                    b.HasIndex("MacAddress")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("TerminalName")
                        .IsUnique();

                    b.ToTable("terminals", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pin_hash");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("PinHash")
                        .IsUnique()
                        .HasFilter("\"pin_hash\" <> ''");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("WebPos.Core.Models.CashAccount", b =>
                {
                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Terminal", "Terminal")
                        .WithMany()
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("WebPos.Core.Models.CashierShift", b =>
                {
                    b.HasOne("WebPos.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Terminal", null)
                        .WithMany()
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebPos.Core.Models.Category", b =>
                {
                    b.HasOne("WebPos.Core.Models.Category", "ParentCategory")
                        .WithMany("InverseParentCategory")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("WebPos.Core.Models.DailyMilkCollection", b =>
                {
                    b.HasOne("WebPos.Core.Models.Party", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("WebPos.Core.Models.DamagedStockLog", b =>
                {
                    b.HasOne("WebPos.Core.Models.ProductBatch", "Batch")
                        .WithMany("DamagedStockLogs")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.User", "LoggedByUser")
                        .WithMany()
                        .HasForeignKey("LoggedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("LoggedByUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebPos.Core.Models.GeneralLedgerEntry", b =>
                {
                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebPos.Core.Models.Party", b =>
                {
                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebPos.Core.Models.PartyLedger", b =>
                {
                    b.HasOne("WebPos.Core.Models.SalesInvoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceNo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebPos.Core.Models.Party", "Party")
                        .WithMany("Ledgers")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.PurchaseOrder", null)
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("WebPos.Core.Models.PartyPaymentAllocation", b =>
                {
                    b.HasOne("WebPos.Core.Models.SalesInvoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceNo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebPos.Core.Models.PartyLedger", "PartyLedger")
                        .WithMany("Allocations")
                        .HasForeignKey("PartyLedgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("PartyLedger");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("WebPos.Core.Models.Product", b =>
                {
                    b.HasOne("WebPos.Core.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebPos.Core.Models.ProductBatch", b =>
                {
                    b.HasOne("WebPos.Core.Models.Product", "Product")
                        .WithMany("Batches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("ProductBatches")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebPos.Core.Models.Party", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("WebPos.Core.Models.ProductionConsumptionItem", b =>
                {
                    b.HasOne("WebPos.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.ProductionLog", "ProductionLog")
                        .WithMany("ConsumptionItems")
                        .HasForeignKey("ProductionLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductionLog");
                });

            modelBuilder.Entity("WebPos.Core.Models.ProductionLog", b =>
                {
                    b.HasOne("WebPos.Core.Models.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("WebPos.Core.Models.ProductionYieldItem", b =>
                {
                    b.HasOne("WebPos.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.ProductionLog", "ProductionLog")
                        .WithMany("YieldItems")
                        .HasForeignKey("ProductionLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.ProductBatch", "TargetBatch")
                        .WithMany("ProductionYieldItems")
                        .HasForeignKey("TargetBatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductionLog");

                    b.Navigation("TargetBatch");
                });

            modelBuilder.Entity("WebPos.Core.Models.PurchaseItem", b =>
                {
                    b.HasOne("WebPos.Core.Models.ProductBatch", "Batch")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebPos.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("WebPos.Core.Models.PurchaseOrder", b =>
                {
                    b.HasOne("WebPos.Core.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Party", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("WebPos.Core.Models.PurchaseReturn", b =>
                {
                    b.HasOne("WebPos.Core.Models.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.PurchaseOrder", "OriginalPurchaseOrder")
                        .WithMany("PurchaseReturns")
                        .HasForeignKey("OriginalPurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Party", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("OriginalPurchaseOrder");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("WebPos.Core.Models.PurchaseReturnItem", b =>
                {
                    b.HasOne("WebPos.Core.Models.ProductBatch", "Batch")
                        .WithMany("PurchaseReturnItems")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.PurchaseReturn", "PurchaseReturn")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Product");

                    b.Navigation("PurchaseReturn");
                });

            modelBuilder.Entity("WebPos.Core.Models.Role", b =>
                {
                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebPos.Core.Models.SalesInvoice", b =>
                {
                    b.HasOne("WebPos.Core.Models.User", "Cashier")
                        .WithMany()
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Party", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebPos.Core.Models.CashierShift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Terminal", "Terminal")
                        .WithMany()
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cashier");

                    b.Navigation("Customer");

                    b.Navigation("Shift");

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("WebPos.Core.Models.SalesItem", b =>
                {
                    b.HasOne("WebPos.Core.Models.ProductBatch", "Batch")
                        .WithMany("SalesItems")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.SalesInvoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebPos.Core.Models.SalesReturn", b =>
                {
                    b.HasOne("WebPos.Core.Models.User", "Cashier")
                        .WithMany()
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Party", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebPos.Core.Models.SalesInvoice", "OriginalInvoice")
                        .WithMany("SalesReturns")
                        .HasForeignKey("OriginalInvoiceNo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cashier");

                    b.Navigation("Customer");

                    b.Navigation("OriginalInvoice");
                });

            modelBuilder.Entity("WebPos.Core.Models.SalesReturnItem", b =>
                {
                    b.HasOne("WebPos.Core.Models.ProductBatch", "Batch")
                        .WithMany("SalesReturnItems")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.SalesReturn", "SalesReturn")
                        .WithMany("Items")
                        .HasForeignKey("SalesReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Product");

                    b.Navigation("SalesReturn");
                });

            modelBuilder.Entity("WebPos.Core.Models.ShiftExpense", b =>
                {
                    b.HasOne("WebPos.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("LoggedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.CashierShift", "Shift")
                        .WithMany("ShiftExpenses")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("WebPos.Core.Models.Terminal", b =>
                {
                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebPos.Core.Models.User", b =>
                {
                    b.HasOne("WebPos.Core.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebPos.Core.Models.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebPos.Core.Models.CashierShift", b =>
                {
                    b.Navigation("ShiftExpenses");
                });

            modelBuilder.Entity("WebPos.Core.Models.Category", b =>
                {
                    b.Navigation("InverseParentCategory");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebPos.Core.Models.Party", b =>
                {
                    b.Navigation("Ledgers");
                });

            modelBuilder.Entity("WebPos.Core.Models.PartyLedger", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("WebPos.Core.Models.Product", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("WebPos.Core.Models.ProductBatch", b =>
                {
                    b.Navigation("DamagedStockLogs");

                    b.Navigation("ProductionYieldItems");

                    b.Navigation("PurchaseItems");

                    b.Navigation("PurchaseReturnItems");

                    b.Navigation("SalesItems");

                    b.Navigation("SalesReturnItems");
                });

            modelBuilder.Entity("WebPos.Core.Models.ProductionLog", b =>
                {
                    b.Navigation("ConsumptionItems");

                    b.Navigation("YieldItems");
                });

            modelBuilder.Entity("WebPos.Core.Models.PurchaseOrder", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("ProductBatches");

                    b.Navigation("PurchaseReturns");
                });

            modelBuilder.Entity("WebPos.Core.Models.PurchaseReturn", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WebPos.Core.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebPos.Core.Models.SalesInvoice", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("SalesReturns");
                });

            modelBuilder.Entity("WebPos.Core.Models.SalesReturn", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
