// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WebPos.Core.Data;

#nullable disable

namespace WebPos.Migrations
{
    [DbContext(typeof(WebPosDbContext))]
    [Migration("20260911110000_AddPosQuickLinkFlags")]
    partial class AddPosQuickLinkFlags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Target model is tracked in WebPosDbContextModelSnapshot.
        }
    }
}
